apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-app-deployment
  labels:
    app: greeting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting-pods
  template:
    metadata:
      labels:
        app: greeting-pods
    spec:
      containers:
        - name: greeting-container
          image: ogleh/my-greeting-app:0.0.2
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_HOST
              value: postgres-service
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_DB
              value: test
            - name: USERNAME
              value: ogleh
            - name: PASSWORD
              value: "1234"


---
apiVersion: v1
kind: Service
metadata:
  name: greeting-app-service
spec:
  selector:
    app: greeting-pods
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30000


