apiVersion: v1
kind: Pod
metadata:
  name: my-postgres-pod
  labels:
    app: postgres-pod
spec:
  containers:
    - name: postgres-container
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: ogleh
        - name: POSTGRES_PASSWORD
          value: "1234"
        - name: POSTGRES_DB
          value: test

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres-pod
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30002
