#version: "3"
#services:
#
#  postgres:
#    container_name: greeting-database
#    image: postgres
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: ogleh
#      POSTGRES_PASSWORD: 1234
#      POSTGRES_DB: test
#    networks:
#      - communication-net
#
#  pg-admin:
#    container_name: greeting-pgadmin
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: oglehmo@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: 1234
#    ports:
#      - "8888:80"
#    networks:
#      - communication-net
#
#



version: "3"
services:

  postgres-service:
    container_name: app-database
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ogleh
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: test
    networks:
      - communication-net

  spring:
    container_name: my-app-container
    image: ogleh/my-greeting-app:0.0.2
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: app-database
      DATABASE_PORT: 5432
      DATABASE_DB: test
      USERNAME: ogleh
      PASSWORD: 1234
    networks:
      - communication-net

networks:
  communication-net:
