version: '3'

services:

  postgres:
    container_name: user-database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - /Users/mohamedogleh/Desktop/my-app/volumes/users-postgres:/var/lib/postgresql/data
    networks:
      - my-network

networks:
  my-network:
    external: true

volumes:
  users-volume:
